### ISSUE TITLE
tasks: backup steps counter

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#705] opened 2016-11-14 09:11 UTC
Steps counter not reset after new task run
<img width="1391" alt="2016-11-14_15-47-31" src="https://cloud.githubusercontent.com/assets/2631910/20258962/d177a2a2-aa84-11e6-9eb4-91ed6d45afb5.png">

**Comment by abolabo** [comment] 2016-11-21 16:33
bad idea. this counter from database. Need to be equal for debugging

**Comment by abantecart** [comment] 2016-11-22 03:37
What is bad idea? Steps count should start from 1. Why do we need to know database ID? 
If you want to show database id it should look like this:

Step #1 (step_id: 11)
Step #2 (step_id: 12)
...

**Comment by abolabo** [comment] 2016-11-22 11:41
There are already presents direct numerations
 "Step 1: Success". 
Look at picture!

**Comment by abantecart** [comment] 2016-11-22 11:51
If sequential count is there, why it does not start from 1 ?

**Comment by abolabo** [comment] 2016-11-24 18:21
duplicate of #705

**Closed by abolabo** 2016-11-24 18:21 UTC
Labels: Active at work, Admin Front
