### ISSUE TITLE
form data lost if one of required fileds empty

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#416] opened 2016-02-23 07:12 UTC
<img width="1237" alt="2016-02-23_14-07-57" src="https://cloud.githubusercontent.com/assets/2631910/13244256/68e15c06-da37-11e5-8475-f3e4a9e20ca9.png">

**Comment by abolabo** [comment] 2016-02-25 14:14
it works correctly! We cannot to preset extensions settings like status. It will confused user.

**Comment by BasaraABC** [comment] 2016-02-26 05:34
You can skip Status. Main problem in other input data lost.

**Comment by abolabo** [comment] 2016-02-28 15:08
duplicate of https://github.com/abantecart/abantecart-src/issues/340
fixed

**Closed** 2016-02-29 10:16 UTC
Labels: Admin Front
