### ISSUE TITLE
Multiselectbox and checkboxgroup can't assign locations

### ISSUE THREAD

**Issue by goatlady102** [abantecart/abantecart-src#1288] opened 2019-06-13 15:20 UTC
The locations fields are missing in checkbox group and multiselectbox.  They need the ability to assign locations to stock  if Admin has more than one location.  Other options work correctly.

These screen shots are from a clean install of 1.2.15, with only options testing.
![image](https://user-images.githubusercontent.com/7943102/59445007-78204d00-8dc4-11e9-8a10-9ae95f287b23.png)

![image](https://user-images.githubusercontent.com/7943102/59445136-b453ad80-8dc4-11e9-9de7-183cf62d3b2a.png)

![image](https://user-images.githubusercontent.com/7943102/59445162-c0d80600-8dc4-11e9-8919-73346447d0f1.png)

Multiselectbox  has the same issue

**Comment by goatlady102** [comment] 2019-06-13 15:24
![image](https://user-images.githubusercontent.com/7943102/59445508-67bca200-8dc5-11e9-8cf5-0eeed9d50ecc.png)

**Comment by BasaraABC** [comment] 2019-06-14 05:12
Hello. This is not a bug. We block location for multi values option types because this do not have sense in relation to stock tracking and stock returns.
Feel free to post you opinion at forum.abantecart.com

**Comment by abantecart** [comment] 2020-04-14 10:27
This problem is created to conceptual issue of option values grouping. Moving forward in v2.0 options will grouped with values to represent one option for the product with multiple values. 
Only group of values (one product variant) can be assigned to location or multiple locations.

**Comment by abantecart** [comment] 2020-04-14 10:30
Currently this problem can be solved with grouping options into parent child, where parent is the group of options that represent one product variant. This parent option can be assigned to locations.

**Comment by abantecart** [comment] 2024-12-24 02:12
Options will be redesigned in version 1.4.2

**Closed** 2024-12-24 02:13 UTC
Labels: discussion
