### ISSUE TITLE
dev: incorrect availability on product page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1253] opened 2019-04-10 11:40 UTC
The total available stock displayed on product page is incorrect see conditions
<img width="790" alt="2in" src="https://user-images.githubusercontent.com/2631910/55875744-0fe49d80-5bc0-11e9-90d9-a66f758e44a4.png">

**Comment by abolabo** [comment] 2019-04-10 15:40
fixed by previous commits

**Comment by BasaraABC** [comment] 2019-04-11 05:31
Issue is not fixed. 
![four](https://user-images.githubusercontent.com/2631910/55932887-a2834c00-5c55-11e9-8e16-9c999102df90.png)

**Comment by BasaraABC** [comment] 2019-04-11 05:33
I think +1 problem affected issue #1251

**Comment by abolabo** [comment] 2019-04-11 15:50
cannot to replicate. need more details

**Comment by abantecart** [comment] 2019-04-12 05:29
@abantecart I think @BasaraABC provided enough details. 
The actual value should be 2 + 3 = 5. This should be accumulative or just show "In stock" in case of options.

**Comment by BasaraABC** [comment] 2019-04-12 05:31
The "Green" option value set Track stock OFF so we should accumulate as "3 in stock" or just "in stock"

**Comment by abantecart** [comment] 2019-04-12 05:33
@abolabo Spent a bit more effort to investigate
The issue is here:
$total_quantity = $this->model_catalog_product->hasAnyStock($product_id);

**Comment by abolabo** [comment] 2019-04-12 07:13
If one of options value have stock tracking OFF and another ON we cannot to calculate common quantity 

![image](https://user-images.githubusercontent.com/1264239/56018717-8641e680-5d0b-11e9-99cb-b958fe2d73ed.png)

![image](https://user-images.githubusercontent.com/1264239/56018728-92c63f00-5d0b-11e9-925e-731890245260.png)

**Comment by BasaraABC** [comment] 2019-04-12 07:20
@abolabo please set Option to be Required.

**Comment by BasaraABC** [comment] 2019-04-12 07:24
See screenshot from my side
![stock222](https://user-images.githubusercontent.com/2631910/56019363-95865b80-5d2e-11e9-881d-b77e65cf843b.png)

**Closed** 2019-04-12 09:20 UTC
Labels: Fixed need QA, dev
